version: 2.1

orbs:
  architect: giantswarm/architect@0.9.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: k8s-api-healthz
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: "quay.io/giantswarm/k8s-api-healthz"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/